"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from panora.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class RemoteIDRequestTypedDict(TypedDict):
    remote_id: str
    

class RemoteIDRequest(BaseModel):
    remote_id: Annotated[str, pydantic.Field(alias="remoteId"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    
