"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from panora.utils import FieldMetadata, PathParamMetadata
from typing import TypedDict
from typing_extensions import Annotated


class StatusRequestTypedDict(TypedDict):
    vertical: str
    

class StatusRequest(BaseModel):
    vertical: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    
