"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import TypedDict


class UnifiedAccountingAttachmentInputTypedDict(TypedDict):
    pass
    

class UnifiedAccountingAttachmentInput(BaseModel):
    pass
    
