"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmEngagementInputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmEngagementInputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmEngagementInputTypedDict(TypedDict):
    type: str
    r"""The type of the engagement. Authorized values are EMAIL, CALL or MEETING"""
    field_mappings: UnifiedCrmEngagementInputFieldMappingsTypedDict
    content: NotRequired[str]
    r"""The content of the engagement"""
    direction: NotRequired[str]
    r"""The direction of the engagement. Authorized values are INBOUND or OUTBOUND"""
    subject: NotRequired[str]
    r"""The subject of the engagement"""
    start_at: NotRequired[datetime]
    r"""The start time of the engagement"""
    end_time: NotRequired[datetime]
    r"""The end time of the engagement"""
    user_id: NotRequired[str]
    r"""The UUID of the user tied to the engagement"""
    company_id: NotRequired[str]
    r"""The UUID of the company tied to the engagement"""
    contacts: NotRequired[List[str]]
    r"""The UUIDs of contacts tied to the engagement object"""
    

class UnifiedCrmEngagementInput(BaseModel):
    type: str
    r"""The type of the engagement. Authorized values are EMAIL, CALL or MEETING"""
    field_mappings: UnifiedCrmEngagementInputFieldMappings
    content: Optional[str] = None
    r"""The content of the engagement"""
    direction: Optional[str] = None
    r"""The direction of the engagement. Authorized values are INBOUND or OUTBOUND"""
    subject: Optional[str] = None
    r"""The subject of the engagement"""
    start_at: Optional[datetime] = None
    r"""The start time of the engagement"""
    end_time: Optional[datetime] = None
    r"""The end time of the engagement"""
    user_id: Optional[str] = None
    r"""The UUID of the user tied to the engagement"""
    company_id: Optional[str] = None
    r"""The UUID of the company tied to the engagement"""
    contacts: Optional[List[str]] = None
    r"""The UUIDs of contacts tied to the engagement object"""
    
