"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingCollectionOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingCollectionOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingCollectionOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingCollectionOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingCollectionOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingCollectionOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingCollectionOutputTypedDict(TypedDict):
    name: str
    r"""The name of the collection"""
    remote_data: UnifiedTicketingCollectionOutputRemoteDataTypedDict
    created_at: UnifiedTicketingCollectionOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingCollectionOutputModifiedAtTypedDict
    description: NotRequired[str]
    r"""The description of the collection"""
    collection_type: NotRequired[str]
    r"""The type of the collection. Authorized values are either PROJECT or LIST"""
    id: NotRequired[str]
    r"""The UUID of the collection"""
    remote_id: NotRequired[str]
    r"""The id of the collection in the context of the 3rd Party"""
    

class UnifiedTicketingCollectionOutput(BaseModel):
    name: str
    r"""The name of the collection"""
    remote_data: UnifiedTicketingCollectionOutputRemoteData
    created_at: UnifiedTicketingCollectionOutputCreatedAt
    modified_at: UnifiedTicketingCollectionOutputModifiedAt
    description: Optional[str] = None
    r"""The description of the collection"""
    collection_type: Optional[str] = None
    r"""The type of the collection. Authorized values are either PROJECT or LIST"""
    id: Optional[str] = None
    r"""The UUID of the collection"""
    remote_id: Optional[str] = None
    r"""The id of the collection in the context of the 3rd Party"""
    
