"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedUserOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedUserOutputFieldMappings(BaseModel):
    pass
    

class UnifiedUserOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedUserOutputRemoteData(BaseModel):
    pass
    

class UnifiedUserOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedUserOutputCreatedAt(BaseModel):
    pass
    

class UnifiedUserOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedUserOutputModifiedAt(BaseModel):
    pass
    

class UnifiedUserOutputTypedDict(TypedDict):
    name: str
    r"""The name of the user"""
    email: str
    r"""The email of the user"""
    is_me: bool
    r"""Whether the user is the one who linked this account."""
    field_mappings: UnifiedUserOutputFieldMappingsTypedDict
    remote_data: UnifiedUserOutputRemoteDataTypedDict
    created_at: UnifiedUserOutputCreatedAtTypedDict
    modified_at: UnifiedUserOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the user"""
    remote_id: NotRequired[str]
    r"""The id of the user in the context of the 3rd Party"""
    

class UnifiedUserOutput(BaseModel):
    name: str
    r"""The name of the user"""
    email: str
    r"""The email of the user"""
    is_me: bool
    r"""Whether the user is the one who linked this account."""
    field_mappings: UnifiedUserOutputFieldMappings
    remote_data: UnifiedUserOutputRemoteData
    created_at: UnifiedUserOutputCreatedAt
    modified_at: UnifiedUserOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the user"""
    remote_id: Optional[str] = None
    r"""The id of the user in the context of the 3rd Party"""
    
