"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingAttachmentOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedTicketingAttachmentOutputFieldMappings(BaseModel):
    pass
    

class UnifiedTicketingAttachmentOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingAttachmentOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingAttachmentOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingAttachmentOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingAttachmentOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingAttachmentOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingAttachmentOutputTypedDict(TypedDict):
    file_name: str
    r"""The file name of the attachment"""
    file_url: str
    r"""The file url of the attachment"""
    uploader: str
    r"""The uploader's UUID of the attachment"""
    field_mappings: UnifiedTicketingAttachmentOutputFieldMappingsTypedDict
    remote_data: UnifiedTicketingAttachmentOutputRemoteDataTypedDict
    created_at: UnifiedTicketingAttachmentOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingAttachmentOutputModifiedAtTypedDict
    ticket_id: NotRequired[str]
    r"""The UUID of the ticket the attachment is tied to"""
    comment_id: NotRequired[str]
    r"""The UUID of the comment the attachment is tied to"""
    id: NotRequired[str]
    r"""The UUID of the attachment"""
    remote_id: NotRequired[str]
    r"""The id of the attachment in the context of the 3rd Party"""
    

class UnifiedTicketingAttachmentOutput(BaseModel):
    file_name: str
    r"""The file name of the attachment"""
    file_url: str
    r"""The file url of the attachment"""
    uploader: str
    r"""The uploader's UUID of the attachment"""
    field_mappings: UnifiedTicketingAttachmentOutputFieldMappings
    remote_data: UnifiedTicketingAttachmentOutputRemoteData
    created_at: UnifiedTicketingAttachmentOutputCreatedAt
    modified_at: UnifiedTicketingAttachmentOutputModifiedAt
    ticket_id: Optional[str] = None
    r"""The UUID of the ticket the attachment is tied to"""
    comment_id: Optional[str] = None
    r"""The UUID of the comment the attachment is tied to"""
    id: Optional[str] = None
    r"""The UUID of the attachment"""
    remote_id: Optional[str] = None
    r"""The id of the attachment in the context of the 3rd Party"""
    
