"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsEeocsOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsEeocsOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsEeocsOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsEeocsOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsEeocsOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsEeocsOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsEeocsOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsEeocsOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsEeocsOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsEeocsOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsEeocsOutputRemoteDataTypedDict
    created_at: UnifiedAtsEeocsOutputCreatedAtTypedDict
    modified_at: UnifiedAtsEeocsOutputModifiedAtTypedDict
    candidate_id: NotRequired[str]
    r"""The UUID of the candidate"""
    submitted_at: NotRequired[datetime]
    r"""The submission date of the EEOC"""
    race: NotRequired[str]
    r"""The race of the candidate"""
    gender: NotRequired[str]
    r"""The gender of the candidate"""
    veteran_status: NotRequired[str]
    r"""The veteran status of the candidate"""
    disability_status: NotRequired[str]
    r"""The disability status of the candidate"""
    id: NotRequired[str]
    r"""The UUID of the EEOC"""
    remote_id: NotRequired[str]
    r"""The remote ID of the EEOC in the context of the 3rd Party"""
    

class UnifiedAtsEeocsOutput(BaseModel):
    field_mappings: UnifiedAtsEeocsOutputFieldMappings
    remote_data: UnifiedAtsEeocsOutputRemoteData
    created_at: UnifiedAtsEeocsOutputCreatedAt
    modified_at: UnifiedAtsEeocsOutputModifiedAt
    candidate_id: Optional[str] = None
    r"""The UUID of the candidate"""
    submitted_at: Optional[datetime] = None
    r"""The submission date of the EEOC"""
    race: Optional[str] = None
    r"""The race of the candidate"""
    gender: Optional[str] = None
    r"""The gender of the candidate"""
    veteran_status: Optional[str] = None
    r"""The veteran status of the candidate"""
    disability_status: Optional[str] = None
    r"""The disability status of the candidate"""
    id: Optional[str] = None
    r"""The UUID of the EEOC"""
    remote_id: Optional[str] = None
    r"""The remote ID of the EEOC in the context of the 3rd Party"""
    
