"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedFilestorageGroupOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageGroupOutputFieldMappings(BaseModel):
    pass
    

class UnifiedFilestorageGroupOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageGroupOutputRemoteData(BaseModel):
    pass
    

class UnifiedFilestorageGroupOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageGroupOutputCreatedAt(BaseModel):
    pass
    

class UnifiedFilestorageGroupOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageGroupOutputModifiedAt(BaseModel):
    pass
    

class UnifiedFilestorageGroupOutputTypedDict(TypedDict):
    name: str
    r"""The name of the group"""
    users: List[str]
    r"""Uuids of users of the group"""
    remote_was_deleted: bool
    r"""Indicates whether or not this object has been deleted in the third party platform."""
    field_mappings: UnifiedFilestorageGroupOutputFieldMappingsTypedDict
    remote_data: UnifiedFilestorageGroupOutputRemoteDataTypedDict
    created_at: UnifiedFilestorageGroupOutputCreatedAtTypedDict
    modified_at: UnifiedFilestorageGroupOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the group"""
    remote_id: NotRequired[str]
    r"""The id of the group in the context of the 3rd Party"""
    

class UnifiedFilestorageGroupOutput(BaseModel):
    name: str
    r"""The name of the group"""
    users: List[str]
    r"""Uuids of users of the group"""
    remote_was_deleted: bool
    r"""Indicates whether or not this object has been deleted in the third party platform."""
    field_mappings: UnifiedFilestorageGroupOutputFieldMappings
    remote_data: UnifiedFilestorageGroupOutputRemoteData
    created_at: UnifiedFilestorageGroupOutputCreatedAt
    modified_at: UnifiedFilestorageGroupOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the group"""
    remote_id: Optional[str] = None
    r"""The id of the group in the context of the 3rd Party"""
    
