"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from .email import Email, EmailTypedDict
from .phone import Phone, PhoneTypedDict
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmContactOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmContactOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmContactOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmContactOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmContactOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmContactOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmContactOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmContactOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmContactOutputTypedDict(TypedDict):
    first_name: str
    r"""The first name of the contact"""
    last_name: str
    r"""The last name of the contact"""
    field_mappings: UnifiedCrmContactOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmContactOutputRemoteDataTypedDict
    created_at: UnifiedCrmContactOutputCreatedAtTypedDict
    modified_at: UnifiedCrmContactOutputModifiedAtTypedDict
    email_addresses: NotRequired[List[EmailTypedDict]]
    r"""The email addresses of the contact"""
    phone_numbers: NotRequired[List[PhoneTypedDict]]
    r"""The phone numbers of the contact"""
    addresses: NotRequired[List[AddressTypedDict]]
    r"""The addresses of the contact"""
    user_id: NotRequired[str]
    r"""The UUID of the user who owns the contact"""
    id: NotRequired[str]
    r"""The UUID of the contact"""
    remote_id: NotRequired[str]
    r"""The id of the contact in the context of the Crm 3rd Party"""
    

class UnifiedCrmContactOutput(BaseModel):
    first_name: str
    r"""The first name of the contact"""
    last_name: str
    r"""The last name of the contact"""
    field_mappings: UnifiedCrmContactOutputFieldMappings
    remote_data: UnifiedCrmContactOutputRemoteData
    created_at: UnifiedCrmContactOutputCreatedAt
    modified_at: UnifiedCrmContactOutputModifiedAt
    email_addresses: Optional[List[Email]] = None
    r"""The email addresses of the contact"""
    phone_numbers: Optional[List[Phone]] = None
    r"""The phone numbers of the contact"""
    addresses: Optional[List[Address]] = None
    r"""The addresses of the contact"""
    user_id: Optional[str] = None
    r"""The UUID of the user who owns the contact"""
    id: Optional[str] = None
    r"""The UUID of the contact"""
    remote_id: Optional[str] = None
    r"""The id of the contact in the context of the Crm 3rd Party"""
    
