"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsActivityOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsActivityOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsActivityOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsActivityOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsActivityOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsActivityOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsActivityOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsActivityOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsActivityOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsActivityOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsActivityOutputRemoteDataTypedDict
    created_at: UnifiedAtsActivityOutputCreatedAtTypedDict
    modified_at: UnifiedAtsActivityOutputModifiedAtTypedDict
    activity_type: NotRequired[str]
    r"""The type of activity"""
    subject: NotRequired[str]
    r"""The subject of the activity"""
    body: NotRequired[str]
    r"""The body of the activity"""
    visibility: NotRequired[str]
    r"""The visibility of the activity"""
    candidate_id: NotRequired[str]
    r"""The UUID of the candidate"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the activity"""
    id: NotRequired[str]
    r"""The UUID of the activity"""
    remote_id: NotRequired[str]
    r"""The remote ID of the activity in the context of the 3rd Party"""
    

class UnifiedAtsActivityOutput(BaseModel):
    field_mappings: UnifiedAtsActivityOutputFieldMappings
    remote_data: UnifiedAtsActivityOutputRemoteData
    created_at: UnifiedAtsActivityOutputCreatedAt
    modified_at: UnifiedAtsActivityOutputModifiedAt
    activity_type: Optional[str] = None
    r"""The type of activity"""
    subject: Optional[str] = None
    r"""The subject of the activity"""
    body: Optional[str] = None
    r"""The body of the activity"""
    visibility: Optional[str] = None
    r"""The visibility of the activity"""
    candidate_id: Optional[str] = None
    r"""The UUID of the candidate"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the activity"""
    id: Optional[str] = None
    r"""The UUID of the activity"""
    remote_id: Optional[str] = None
    r"""The remote ID of the activity in the context of the 3rd Party"""
    
