"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmNoteOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmNoteOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmNoteOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmNoteOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmNoteOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmNoteOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmNoteOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmNoteOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmNoteOutputTypedDict(TypedDict):
    content: str
    r"""The content of the note"""
    field_mappings: UnifiedCrmNoteOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmNoteOutputRemoteDataTypedDict
    created_at: UnifiedCrmNoteOutputCreatedAtTypedDict
    modified_at: UnifiedCrmNoteOutputModifiedAtTypedDict
    user_id: NotRequired[str]
    r"""The UUID of the user tied the note"""
    company_id: NotRequired[str]
    r"""The UUID of the company tied to the note"""
    contact_id: NotRequired[str]
    r"""The UUID fo the contact tied to the note"""
    deal_id: NotRequired[str]
    r"""The UUID of the deal tied to the note"""
    id: NotRequired[str]
    r"""The UUID of the note"""
    remote_id: NotRequired[str]
    r"""The id of the note in the context of the Crm 3rd Party"""
    

class UnifiedCrmNoteOutput(BaseModel):
    content: str
    r"""The content of the note"""
    field_mappings: UnifiedCrmNoteOutputFieldMappings
    remote_data: UnifiedCrmNoteOutputRemoteData
    created_at: UnifiedCrmNoteOutputCreatedAt
    modified_at: UnifiedCrmNoteOutputModifiedAt
    user_id: Optional[str] = None
    r"""The UUID of the user tied the note"""
    company_id: Optional[str] = None
    r"""The UUID of the company tied to the note"""
    contact_id: Optional[str] = None
    r"""The UUID fo the contact tied to the note"""
    deal_id: Optional[str] = None
    r"""The UUID of the deal tied to the note"""
    id: Optional[str] = None
    r"""The UUID of the note"""
    remote_id: Optional[str] = None
    r"""The id of the note in the context of the Crm 3rd Party"""
    
