"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsJobinterviewstageOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobinterviewstageOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsJobinterviewstageOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobinterviewstageOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsJobinterviewstageOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobinterviewstageOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsJobinterviewstageOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobinterviewstageOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsJobinterviewstageOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsJobinterviewstageOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsJobinterviewstageOutputRemoteDataTypedDict
    created_at: UnifiedAtsJobinterviewstageOutputCreatedAtTypedDict
    modified_at: UnifiedAtsJobinterviewstageOutputModifiedAtTypedDict
    name: NotRequired[str]
    r"""The name of the job interview stage"""
    stage_order: NotRequired[float]
    r"""The order of the stage"""
    job_id: NotRequired[str]
    r"""The UUID of the job"""
    id: NotRequired[str]
    r"""The UUID of the job interview stage"""
    remote_id: NotRequired[str]
    r"""The remote ID of the job interview stage in the context of the 3rd Party"""
    

class UnifiedAtsJobinterviewstageOutput(BaseModel):
    field_mappings: UnifiedAtsJobinterviewstageOutputFieldMappings
    remote_data: UnifiedAtsJobinterviewstageOutputRemoteData
    created_at: UnifiedAtsJobinterviewstageOutputCreatedAt
    modified_at: UnifiedAtsJobinterviewstageOutputModifiedAt
    name: Optional[str] = None
    r"""The name of the job interview stage"""
    stage_order: Optional[float] = None
    r"""The order of the stage"""
    job_id: Optional[str] = None
    r"""The UUID of the job"""
    id: Optional[str] = None
    r"""The UUID of the job interview stage"""
    remote_id: Optional[str] = None
    r"""The remote ID of the job interview stage in the context of the 3rd Party"""
    
