"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsJobOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsJobOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsJobOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsJobOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsJobOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsJobOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsJobOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsJobOutputRemoteDataTypedDict
    created_at: UnifiedAtsJobOutputCreatedAtTypedDict
    modified_at: UnifiedAtsJobOutputModifiedAtTypedDict
    name: NotRequired[str]
    r"""The name of the job"""
    description: NotRequired[str]
    r"""The description of the job"""
    code: NotRequired[str]
    r"""The code of the job"""
    status: NotRequired[str]
    r"""The status of the job"""
    type: NotRequired[str]
    r"""The type of the job"""
    confidential: NotRequired[bool]
    r"""Whether the job is confidential"""
    departments: NotRequired[List[str]]
    r"""The departments UUIDs associated with the job"""
    offices: NotRequired[List[str]]
    r"""The offices UUIDs associated with the job"""
    managers: NotRequired[List[str]]
    r"""The managers UUIDs associated with the job"""
    recruiters: NotRequired[List[str]]
    r"""The recruiters UUIDs associated with the job"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the job"""
    remote_updated_at: NotRequired[datetime]
    r"""The remote modification date of the job"""
    id: NotRequired[str]
    r"""The UUID of the job"""
    remote_id: NotRequired[str]
    r"""The remote ID of the job in the context of the 3rd Party"""
    

class UnifiedAtsJobOutput(BaseModel):
    field_mappings: UnifiedAtsJobOutputFieldMappings
    remote_data: UnifiedAtsJobOutputRemoteData
    created_at: UnifiedAtsJobOutputCreatedAt
    modified_at: UnifiedAtsJobOutputModifiedAt
    name: Optional[str] = None
    r"""The name of the job"""
    description: Optional[str] = None
    r"""The description of the job"""
    code: Optional[str] = None
    r"""The code of the job"""
    status: Optional[str] = None
    r"""The status of the job"""
    type: Optional[str] = None
    r"""The type of the job"""
    confidential: Optional[bool] = None
    r"""Whether the job is confidential"""
    departments: Optional[List[str]] = None
    r"""The departments UUIDs associated with the job"""
    offices: Optional[List[str]] = None
    r"""The offices UUIDs associated with the job"""
    managers: Optional[List[str]] = None
    r"""The managers UUIDs associated with the job"""
    recruiters: Optional[List[str]] = None
    r"""The recruiters UUIDs associated with the job"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the job"""
    remote_updated_at: Optional[datetime] = None
    r"""The remote modification date of the job"""
    id: Optional[str] = None
    r"""The UUID of the job"""
    remote_id: Optional[str] = None
    r"""The remote ID of the job in the context of the 3rd Party"""
    
