"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmTaskOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmTaskOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmTaskOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmTaskOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmTaskOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmTaskOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmTaskOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmTaskOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmTaskOutputTypedDict(TypedDict):
    subject: str
    r"""The subject of the task"""
    content: str
    r"""The content of the task"""
    status: str
    r"""The status of the task. Authorized values are PENDING, COMPLETED."""
    field_mappings: UnifiedCrmTaskOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmTaskOutputRemoteDataTypedDict
    created_at: UnifiedCrmTaskOutputCreatedAtTypedDict
    modified_at: UnifiedCrmTaskOutputModifiedAtTypedDict
    due_date: NotRequired[datetime]
    r"""The due date of the task"""
    finished_date: NotRequired[datetime]
    r"""The finished date of the task"""
    user_id: NotRequired[str]
    r"""The UUID of the user tied to the task"""
    company_id: NotRequired[str]
    r"""The UUID fo the company tied to the task"""
    deal_id: NotRequired[str]
    r"""The UUID of the deal tied to the task"""
    id: NotRequired[str]
    r"""The UUID of the task"""
    remote_id: NotRequired[str]
    r"""The id of the task in the context of the Crm 3rd Party"""
    

class UnifiedCrmTaskOutput(BaseModel):
    subject: str
    r"""The subject of the task"""
    content: str
    r"""The content of the task"""
    status: str
    r"""The status of the task. Authorized values are PENDING, COMPLETED."""
    field_mappings: UnifiedCrmTaskOutputFieldMappings
    remote_data: UnifiedCrmTaskOutputRemoteData
    created_at: UnifiedCrmTaskOutputCreatedAt
    modified_at: UnifiedCrmTaskOutputModifiedAt
    due_date: Optional[datetime] = None
    r"""The due date of the task"""
    finished_date: Optional[datetime] = None
    r"""The finished date of the task"""
    user_id: Optional[str] = None
    r"""The UUID of the user tied to the task"""
    company_id: Optional[str] = None
    r"""The UUID fo the company tied to the task"""
    deal_id: Optional[str] = None
    r"""The UUID of the deal tied to the task"""
    id: Optional[str] = None
    r"""The UUID of the task"""
    remote_id: Optional[str] = None
    r"""The id of the task in the context of the Crm 3rd Party"""
    
