"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingUserOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedTicketingUserOutputFieldMappings(BaseModel):
    pass
    

class UnifiedTicketingUserOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingUserOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingUserOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingUserOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingUserOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingUserOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingUserOutputTypedDict(TypedDict):
    name: str
    r"""The name of the user"""
    email_address: str
    r"""The email address of the user"""
    field_mappings: UnifiedTicketingUserOutputFieldMappingsTypedDict
    remote_data: UnifiedTicketingUserOutputRemoteDataTypedDict
    created_at: UnifiedTicketingUserOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingUserOutputModifiedAtTypedDict
    teams: NotRequired[List[str]]
    r"""The teams whose the user is part of"""
    account_id: NotRequired[str]
    r"""The account or organization the user is part of"""
    id: NotRequired[str]
    r"""The UUID of the user"""
    remote_id: NotRequired[str]
    r"""The id of the user in the context of the 3rd Party"""
    

class UnifiedTicketingUserOutput(BaseModel):
    name: str
    r"""The name of the user"""
    email_address: str
    r"""The email address of the user"""
    field_mappings: UnifiedTicketingUserOutputFieldMappings
    remote_data: UnifiedTicketingUserOutputRemoteData
    created_at: UnifiedTicketingUserOutputCreatedAt
    modified_at: UnifiedTicketingUserOutputModifiedAt
    teams: Optional[List[str]] = None
    r"""The teams whose the user is part of"""
    account_id: Optional[str] = None
    r"""The account or organization the user is part of"""
    id: Optional[str] = None
    r"""The UUID of the user"""
    remote_id: Optional[str] = None
    r"""The id of the user in the context of the 3rd Party"""
    
