"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmTaskInputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmTaskInputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmTaskInputTypedDict(TypedDict):
    subject: str
    r"""The subject of the task"""
    content: str
    r"""The content of the task"""
    status: str
    r"""The status of the task. Authorized values are PENDING, COMPLETED."""
    field_mappings: UnifiedCrmTaskInputFieldMappingsTypedDict
    due_date: NotRequired[datetime]
    r"""The due date of the task"""
    finished_date: NotRequired[datetime]
    r"""The finished date of the task"""
    user_id: NotRequired[str]
    r"""The UUID of the user tied to the task"""
    company_id: NotRequired[str]
    r"""The UUID fo the company tied to the task"""
    deal_id: NotRequired[str]
    r"""The UUID of the deal tied to the task"""
    

class UnifiedCrmTaskInput(BaseModel):
    subject: str
    r"""The subject of the task"""
    content: str
    r"""The content of the task"""
    status: str
    r"""The status of the task. Authorized values are PENDING, COMPLETED."""
    field_mappings: UnifiedCrmTaskInputFieldMappings
    due_date: Optional[datetime] = None
    r"""The due date of the task"""
    finished_date: Optional[datetime] = None
    r"""The finished date of the task"""
    user_id: Optional[str] = None
    r"""The UUID of the user tied to the task"""
    company_id: Optional[str] = None
    r"""The UUID fo the company tied to the task"""
    deal_id: Optional[str] = None
    r"""The UUID of the deal tied to the task"""
    
