"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsInterviewInputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsInterviewInputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsInterviewInputTypedDict(TypedDict):
    field_mappings: UnifiedAtsInterviewInputFieldMappingsTypedDict
    status: NotRequired[str]
    r"""The status of the interview"""
    application_id: NotRequired[str]
    r"""The UUID of the application"""
    job_interview_stage_id: NotRequired[str]
    r"""The UUID of the job interview stage"""
    organized_by: NotRequired[str]
    r"""The UUID of the organizer"""
    interviewers: NotRequired[List[str]]
    r"""The UUIDs of the interviewers"""
    location: NotRequired[str]
    r"""The location of the interview"""
    start_at: NotRequired[datetime]
    r"""The start date and time of the interview"""
    end_at: NotRequired[datetime]
    r"""The end date and time of the interview"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the interview"""
    remote_updated_at: NotRequired[datetime]
    r"""The remote modification date of the interview"""
    

class UnifiedAtsInterviewInput(BaseModel):
    field_mappings: UnifiedAtsInterviewInputFieldMappings
    status: Optional[str] = None
    r"""The status of the interview"""
    application_id: Optional[str] = None
    r"""The UUID of the application"""
    job_interview_stage_id: Optional[str] = None
    r"""The UUID of the job interview stage"""
    organized_by: Optional[str] = None
    r"""The UUID of the organizer"""
    interviewers: Optional[List[str]] = None
    r"""The UUIDs of the interviewers"""
    location: Optional[str] = None
    r"""The location of the interview"""
    start_at: Optional[datetime] = None
    r"""The start date and time of the interview"""
    end_at: Optional[datetime] = None
    r"""The end date and time of the interview"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the interview"""
    remote_updated_at: Optional[datetime] = None
    r"""The remote modification date of the interview"""
    
