"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsOfferOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfferOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsOfferOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfferOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsOfferOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfferOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsOfferOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfferOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsOfferOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsOfferOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsOfferOutputRemoteDataTypedDict
    created_at: UnifiedAtsOfferOutputCreatedAtTypedDict
    modified_at: UnifiedAtsOfferOutputModifiedAtTypedDict
    created_by: NotRequired[str]
    r"""The UUID of the creator"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the offer"""
    closed_at: NotRequired[datetime]
    r"""The closing date of the offer"""
    sent_at: NotRequired[datetime]
    r"""The sending date of the offer"""
    start_date: NotRequired[datetime]
    r"""The start date of the offer"""
    status: NotRequired[str]
    r"""The status of the offer"""
    application_id: NotRequired[str]
    r"""The UUID of the application"""
    id: NotRequired[str]
    r"""The UUID of the offer"""
    remote_id: NotRequired[str]
    r"""The remote ID of the offer in the context of the 3rd Party"""
    

class UnifiedAtsOfferOutput(BaseModel):
    field_mappings: UnifiedAtsOfferOutputFieldMappings
    remote_data: UnifiedAtsOfferOutputRemoteData
    created_at: UnifiedAtsOfferOutputCreatedAt
    modified_at: UnifiedAtsOfferOutputModifiedAt
    created_by: Optional[str] = None
    r"""The UUID of the creator"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the offer"""
    closed_at: Optional[datetime] = None
    r"""The closing date of the offer"""
    sent_at: Optional[datetime] = None
    r"""The sending date of the offer"""
    start_date: Optional[datetime] = None
    r"""The start date of the offer"""
    status: Optional[str] = None
    r"""The status of the offer"""
    application_id: Optional[str] = None
    r"""The UUID of the application"""
    id: Optional[str] = None
    r"""The UUID of the offer"""
    remote_id: Optional[str] = None
    r"""The remote ID of the offer in the context of the 3rd Party"""
    
