"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from panora.activities import Activities
from panora.applications import Applications
from panora.attachments import Attachments
from panora.candidates import Candidates
from panora.departments import Departments
from panora.eeocs import Eeocs
from panora.interviews import Interviews
from panora.jobinterviewstages import Jobinterviewstages
from panora.jobs import Jobs
from panora.offers import Offers
from panora.offices import Offices
from panora.panora_ats_users import PanoraAtsUsers
from panora.panora_tags import PanoraTags
from panora.rejectreasons import Rejectreasons
from panora.scorecards import Scorecards

class Ats(BaseSDK):
    activities: Activities
    applications: Applications
    attachments: Attachments
    candidates: Candidates
    departments: Departments
    interviews: Interviews
    jobinterviewstages: Jobinterviewstages
    jobs: Jobs
    offers: Offers
    offices: Offices
    rejectreasons: Rejectreasons
    scorecards: Scorecards
    tags: PanoraTags
    users: PanoraAtsUsers
    eeocs: Eeocs
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.activities = Activities(self.sdk_configuration)
        self.applications = Applications(self.sdk_configuration)
        self.attachments = Attachments(self.sdk_configuration)
        self.candidates = Candidates(self.sdk_configuration)
        self.departments = Departments(self.sdk_configuration)
        self.interviews = Interviews(self.sdk_configuration)
        self.jobinterviewstages = Jobinterviewstages(self.sdk_configuration)
        self.jobs = Jobs(self.sdk_configuration)
        self.offers = Offers(self.sdk_configuration)
        self.offices = Offices(self.sdk_configuration)
        self.rejectreasons = Rejectreasons(self.sdk_configuration)
        self.scorecards = Scorecards(self.sdk_configuration)
        self.tags = PanoraTags(self.sdk_configuration)
        self.users = PanoraAtsUsers(self.sdk_configuration)
        self.eeocs = Eeocs(self.sdk_configuration)
    
