"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from panora.drives import Drives
from panora.files import Files
from panora.folders import Folders
from panora.panora_filestorage_users import PanoraFilestorageUsers
from panora.panora_groups import PanoraGroups

class Filestorage(BaseSDK):
    drives: Drives
    files: Files
    folders: Folders
    groups: PanoraGroups
    users: PanoraFilestorageUsers
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.drives = Drives(self.sdk_configuration)
        self.files = Files(self.sdk_configuration)
        self.folders = Folders(self.sdk_configuration)
        self.groups = PanoraGroups(self.sdk_configuration)
        self.users = PanoraFilestorageUsers(self.sdk_configuration)
    
