"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from panora.actions import Actions
from panora.automations import Automations
from panora.campaigns import Campaigns
from panora.emails import Emails
from panora.events import Events
from panora.lists import Lists
from panora.messages import Messages
from panora.panora_marketingautomation_contacts import PanoraMarketingautomationContacts
from panora.panora_marketingautomation_users import PanoraMarketingautomationUsers
from panora.templates import Templates

class Marketingautomation(BaseSDK):
    actions: Actions
    automations: Automations
    campaigns: Campaigns
    contacts: PanoraMarketingautomationContacts
    emails: Emails
    events: Events
    lists: Lists
    messages: Messages
    templates: Templates
    users: PanoraMarketingautomationUsers
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.actions = Actions(self.sdk_configuration)
        self.automations = Automations(self.sdk_configuration)
        self.campaigns = Campaigns(self.sdk_configuration)
        self.contacts = PanoraMarketingautomationContacts(self.sdk_configuration)
        self.emails = Emails(self.sdk_configuration)
        self.events = Events(self.sdk_configuration)
        self.lists = Lists(self.sdk_configuration)
        self.messages = Messages(self.sdk_configuration)
        self.templates = Templates(self.sdk_configuration)
        self.users = PanoraMarketingautomationUsers(self.sdk_configuration)
    
