"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from panora.accounts import Accounts
from panora.collections import Collections
from panora.comments import Comments
from panora.contacts import Contacts
from panora.panora_ticketing_attachments import PanoraTicketingAttachments
from panora.tags import Tags
from panora.teams import Teams
from panora.tickets import Tickets
from panora.users import Users

class Ticketing(BaseSDK):
    tickets: Tickets
    users: Users
    accounts: Accounts
    contacts: Contacts
    collections: Collections
    comments: Comments
    tags: Tags
    teams: Teams
    attachments: PanoraTicketingAttachments
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.tickets = Tickets(self.sdk_configuration)
        self.users = Users(self.sdk_configuration)
        self.accounts = Accounts(self.sdk_configuration)
        self.contacts = Contacts(self.sdk_configuration)
        self.collections = Collections(self.sdk_configuration)
        self.comments = Comments(self.sdk_configuration)
        self.tags = Tags(self.sdk_configuration)
        self.teams = Teams(self.sdk_configuration)
        self.attachments = PanoraTicketingAttachments(self.sdk_configuration)
    
