"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import TypedDict


class CreateLinkedUserDtoTypedDict(TypedDict):
    linked_user_origin_id: str
    alias: str
    

class CreateLinkedUserDto(BaseModel):
    linked_user_origin_id: str
    alias: str
    
