"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import TypedDict


class LoginDtoTypedDict(TypedDict):
    id_user: str
    email: str
    password_hash: str
    

class LoginDto(BaseModel):
    id_user: str
    email: str
    password_hash: str
    
