"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import TypedDict


class PassThroughResponseDataTypedDict(TypedDict):
    pass
    

class PassThroughResponseData(BaseModel):
    pass
    

class PassThroughResponseTypedDict(TypedDict):
    url: Nullable[str]
    status: Nullable[float]
    data: Nullable[PassThroughResponseDataTypedDict]
    

class PassThroughResponse(BaseModel):
    url: Nullable[str]
    status: Nullable[float]
    data: Nullable[PassThroughResponseData]
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["url", "status", "data"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        
