"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, TypedDict


class RagQueryOutputTypedDict(TypedDict):
    chunk: str
    r"""The chunk which matches the embed query"""
    metadata: Nullable[Dict[str, Any]]
    r"""The metadata tied to the chunk"""
    score: Nullable[float]
    r"""The score"""
    embedding: Nullable[List[float]]
    r"""The embedding of the relevant chunk"""
    

class RagQueryOutput(BaseModel):
    chunk: str
    r"""The chunk which matches the embed query"""
    metadata: Nullable[Dict[str, Any]]
    r"""The metadata tied to the chunk"""
    score: Nullable[float]
    r"""The score"""
    embedding: Nullable[List[float]]
    r"""The embedding of the relevant chunk"""
    
    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["metadata", "score", "embedding"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields
                or (
                    k in optional_fields
                    and k in nullable_fields
                    and (
                        self.__pydantic_fields_set__.intersection({n})
                        or k in null_default_fields
                    )  # pylint: disable=no-member
                )
            ):
                m[k] = val

        return m
        
