"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from panora_sdk.utils import FieldMetadata, QueryParamMetadata
from typing import TypedDict
from typing_extensions import Annotated


class RetrieveLinkedUserRequestTypedDict(TypedDict):
    id: str
    

class RetrieveLinkedUserRequest(BaseModel):
    id: Annotated[str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    
