"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from panora_sdk.utils import FieldMetadata, SecurityMetadata
from typing import TypedDict
from typing_extensions import Annotated


class SecurityTypedDict(TypedDict):
    bearer: str
    

class Security(BaseModel):
    bearer: Annotated[str, FieldMetadata(security=SecurityMetadata(scheme=True, scheme_type="http", sub_type="bearer", field_name="Authorization"))]
    
