"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsRejectreasonOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsRejectreasonOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsRejectreasonOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsRejectreasonOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsRejectreasonOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsRejectreasonOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsRejectreasonOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsRejectreasonOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsRejectreasonOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsRejectreasonOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsRejectreasonOutputRemoteDataTypedDict
    created_at: UnifiedAtsRejectreasonOutputCreatedAtTypedDict
    modified_at: UnifiedAtsRejectreasonOutputModifiedAtTypedDict
    name: NotRequired[str]
    r"""The name of the reject reason"""
    id: NotRequired[str]
    r"""The UUID of the reject reason"""
    remote_id: NotRequired[str]
    r"""The remote ID of the reject reason in the context of the 3rd Party"""
    

class UnifiedAtsRejectreasonOutput(BaseModel):
    field_mappings: UnifiedAtsRejectreasonOutputFieldMappings
    remote_data: UnifiedAtsRejectreasonOutputRemoteData
    created_at: UnifiedAtsRejectreasonOutputCreatedAt
    modified_at: UnifiedAtsRejectreasonOutputModifiedAt
    name: Optional[str] = None
    r"""The name of the reject reason"""
    id: Optional[str] = None
    r"""The UUID of the reject reason"""
    remote_id: Optional[str] = None
    r"""The remote ID of the reject reason in the context of the 3rd Party"""
    
