"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingContactOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedTicketingContactOutputFieldMappings(BaseModel):
    pass
    

class UnifiedTicketingContactOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingContactOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingContactOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingContactOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingContactOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingContactOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingContactOutputTypedDict(TypedDict):
    name: str
    r"""The name of the contact"""
    email_address: str
    r"""The email address of the contact"""
    field_mappings: UnifiedTicketingContactOutputFieldMappingsTypedDict
    remote_data: UnifiedTicketingContactOutputRemoteDataTypedDict
    created_at: UnifiedTicketingContactOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingContactOutputModifiedAtTypedDict
    phone_number: NotRequired[str]
    r"""The phone number of the contact"""
    details: NotRequired[str]
    r"""The details of the contact"""
    id: NotRequired[str]
    r"""The UUID of the contact"""
    remote_id: NotRequired[str]
    r"""The id of the contact in the context of the 3rd Party"""
    

class UnifiedTicketingContactOutput(BaseModel):
    name: str
    r"""The name of the contact"""
    email_address: str
    r"""The email address of the contact"""
    field_mappings: UnifiedTicketingContactOutputFieldMappings
    remote_data: UnifiedTicketingContactOutputRemoteData
    created_at: UnifiedTicketingContactOutputCreatedAt
    modified_at: UnifiedTicketingContactOutputModifiedAt
    phone_number: Optional[str] = None
    r"""The phone number of the contact"""
    details: Optional[str] = None
    r"""The details of the contact"""
    id: Optional[str] = None
    r"""The UUID of the contact"""
    remote_id: Optional[str] = None
    r"""The id of the contact in the context of the 3rd Party"""
    
