"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingTeamOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTeamOutputFieldMappings(BaseModel):
    pass
    

class UnifiedTicketingTeamOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTeamOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingTeamOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTeamOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingTeamOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTeamOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingTeamOutputTypedDict(TypedDict):
    name: str
    r"""The name of the team"""
    field_mappings: UnifiedTicketingTeamOutputFieldMappingsTypedDict
    remote_data: UnifiedTicketingTeamOutputRemoteDataTypedDict
    created_at: UnifiedTicketingTeamOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingTeamOutputModifiedAtTypedDict
    description: NotRequired[str]
    r"""The description of the team"""
    id: NotRequired[str]
    r"""The UUID of the team"""
    remote_id: NotRequired[str]
    r"""The id of the team in the context of the 3rd Party"""
    

class UnifiedTicketingTeamOutput(BaseModel):
    name: str
    r"""The name of the team"""
    field_mappings: UnifiedTicketingTeamOutputFieldMappings
    remote_data: UnifiedTicketingTeamOutputRemoteData
    created_at: UnifiedTicketingTeamOutputCreatedAt
    modified_at: UnifiedTicketingTeamOutputModifiedAt
    description: Optional[str] = None
    r"""The description of the team"""
    id: Optional[str] = None
    r"""The UUID of the team"""
    remote_id: Optional[str] = None
    r"""The id of the team in the context of the 3rd Party"""
    
