"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ItemsModelTypedDict(TypedDict):
    r"""The items in the order"""
    
    

class ItemsModel(BaseModel):
    r"""The items in the order"""
    
    

class UnifiedEcommerceOrderOutputFieldMappingsTypedDict(TypedDict):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceOrderOutputFieldMappings(BaseModel):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceOrderOutputRemoteDataTypedDict(TypedDict):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceOrderOutputRemoteData(BaseModel):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceOrderOutputTypedDict(TypedDict):
    order_status: NotRequired[str]
    r"""The status of the order"""
    order_number: NotRequired[str]
    r"""The number of the order"""
    payment_status: NotRequired[str]
    r"""The payment status of the order"""
    currency: NotRequired[str]
    r"""The currency of the order. Authorized value must be of type CurrencyCode (ISO 4217)"""
    total_price: NotRequired[float]
    r"""The total price of the order"""
    total_discount: NotRequired[float]
    r"""The total discount on the order"""
    total_shipping: NotRequired[float]
    r"""The total shipping cost of the order"""
    total_tax: NotRequired[float]
    r"""The total tax on the order"""
    fulfillment_status: NotRequired[str]
    r"""The fulfillment status of the order"""
    customer_id: NotRequired[str]
    r"""The UUID of the customer associated with the order"""
    items: NotRequired[ItemsModelTypedDict]
    r"""The items in the order"""
    field_mappings: NotRequired[UnifiedEcommerceOrderOutputFieldMappingsTypedDict]
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: NotRequired[str]
    r"""The UUID of the order"""
    remote_id: NotRequired[str]
    r"""The remote ID of the order in the context of the 3rd Party"""
    remote_data: NotRequired[UnifiedEcommerceOrderOutputRemoteDataTypedDict]
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: NotRequired[str]
    r"""The created date of the object"""
    modified_at: NotRequired[str]
    r"""The modified date of the object"""
    

class UnifiedEcommerceOrderOutput(BaseModel):
    order_status: Optional[str] = None
    r"""The status of the order"""
    order_number: Optional[str] = None
    r"""The number of the order"""
    payment_status: Optional[str] = None
    r"""The payment status of the order"""
    currency: Optional[str] = None
    r"""The currency of the order. Authorized value must be of type CurrencyCode (ISO 4217)"""
    total_price: Optional[float] = None
    r"""The total price of the order"""
    total_discount: Optional[float] = None
    r"""The total discount on the order"""
    total_shipping: Optional[float] = None
    r"""The total shipping cost of the order"""
    total_tax: Optional[float] = None
    r"""The total tax on the order"""
    fulfillment_status: Optional[str] = None
    r"""The fulfillment status of the order"""
    customer_id: Optional[str] = None
    r"""The UUID of the customer associated with the order"""
    items: Optional[ItemsModel] = None
    r"""The items in the order"""
    field_mappings: Optional[UnifiedEcommerceOrderOutputFieldMappings] = None
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: Optional[str] = None
    r"""The UUID of the order"""
    remote_id: Optional[str] = None
    r"""The remote ID of the order in the context of the 3rd Party"""
    remote_data: Optional[UnifiedEcommerceOrderOutputRemoteData] = None
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: Optional[str] = None
    r"""The created date of the object"""
    modified_at: Optional[str] = None
    r"""The modified date of the object"""
    
