"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedEcommerceProductInputVariantsTypedDict(TypedDict):
    pass
    

class UnifiedEcommerceProductInputVariants(BaseModel):
    pass
    

class UnifiedEcommerceProductInputFieldMappingsTypedDict(TypedDict):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceProductInputFieldMappings(BaseModel):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceProductInputTypedDict(TypedDict):
    product_url: NotRequired[str]
    r"""The URL of the product"""
    product_type: NotRequired[str]
    r"""The type of the product"""
    product_status: NotRequired[str]
    r"""The status of the product. Either ACTIVE, DRAFT OR ARCHIVED."""
    images_urls: NotRequired[List[str]]
    r"""The URLs of the product images"""
    description: NotRequired[str]
    r"""The description of the product"""
    vendor: NotRequired[str]
    r"""The vendor of the product"""
    variants: NotRequired[List[UnifiedEcommerceProductInputVariantsTypedDict]]
    r"""The variants of the product"""
    tags: NotRequired[List[str]]
    r"""The tags associated with the product"""
    field_mappings: NotRequired[UnifiedEcommerceProductInputFieldMappingsTypedDict]
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    

class UnifiedEcommerceProductInput(BaseModel):
    product_url: Optional[str] = None
    r"""The URL of the product"""
    product_type: Optional[str] = None
    r"""The type of the product"""
    product_status: Optional[str] = None
    r"""The status of the product. Either ACTIVE, DRAFT OR ARCHIVED."""
    images_urls: Optional[List[str]] = None
    r"""The URLs of the product images"""
    description: Optional[str] = None
    r"""The description of the product"""
    vendor: Optional[str] = None
    r"""The vendor of the product"""
    variants: Optional[List[UnifiedEcommerceProductInputVariants]] = None
    r"""The variants of the product"""
    tags: Optional[List[str]] = None
    r"""The tags associated with the product"""
    field_mappings: Optional[UnifiedEcommerceProductInputFieldMappings] = None
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
