"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedTicketingTagOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTagOutputFieldMappings(BaseModel):
    pass
    

class UnifiedTicketingTagOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTagOutputRemoteData(BaseModel):
    pass
    

class UnifiedTicketingTagOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTagOutputCreatedAt(BaseModel):
    pass
    

class UnifiedTicketingTagOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedTicketingTagOutputModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingTagOutputTypedDict(TypedDict):
    name: str
    r"""The name of the tag"""
    field_mappings: UnifiedTicketingTagOutputFieldMappingsTypedDict
    remote_data: UnifiedTicketingTagOutputRemoteDataTypedDict
    created_at: UnifiedTicketingTagOutputCreatedAtTypedDict
    modified_at: UnifiedTicketingTagOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the tag"""
    remote_id: NotRequired[str]
    r"""The id of the tag in the context of the 3rd Party"""
    

class UnifiedTicketingTagOutput(BaseModel):
    name: str
    r"""The name of the tag"""
    field_mappings: UnifiedTicketingTagOutputFieldMappings
    remote_data: UnifiedTicketingTagOutputRemoteData
    created_at: UnifiedTicketingTagOutputCreatedAt
    modified_at: UnifiedTicketingTagOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the tag"""
    remote_id: Optional[str] = None
    r"""The id of the tag in the context of the 3rd Party"""
    
