"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class VariantsTypedDict(TypedDict):
    pass
    

class Variants(BaseModel):
    pass
    

class FieldMappingsModelTypedDict(TypedDict):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class FieldMappingsModel(BaseModel):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class RemoteDataTypedDict(TypedDict):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class RemoteData(BaseModel):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceProductOutputTypedDict(TypedDict):
    product_url: NotRequired[str]
    r"""The URL of the product"""
    product_type: NotRequired[str]
    r"""The type of the product"""
    product_status: NotRequired[str]
    r"""The status of the product. Either ACTIVE, DRAFT OR ARCHIVED."""
    images_urls: NotRequired[List[str]]
    r"""The URLs of the product images"""
    description: NotRequired[str]
    r"""The description of the product"""
    vendor: NotRequired[str]
    r"""The vendor of the product"""
    variants: NotRequired[List[VariantsTypedDict]]
    r"""The variants of the product"""
    tags: NotRequired[List[str]]
    r"""The tags associated with the product"""
    field_mappings: NotRequired[FieldMappingsModelTypedDict]
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: NotRequired[str]
    r"""The UUID of the product"""
    remote_id: NotRequired[str]
    r"""The remote ID of the product in the context of the 3rd Party"""
    remote_data: NotRequired[RemoteDataTypedDict]
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: NotRequired[str]
    r"""The created date of the object"""
    modified_at: NotRequired[str]
    r"""The modified date of the object"""
    

class UnifiedEcommerceProductOutput(BaseModel):
    product_url: Optional[str] = None
    r"""The URL of the product"""
    product_type: Optional[str] = None
    r"""The type of the product"""
    product_status: Optional[str] = None
    r"""The status of the product. Either ACTIVE, DRAFT OR ARCHIVED."""
    images_urls: Optional[List[str]] = None
    r"""The URLs of the product images"""
    description: Optional[str] = None
    r"""The description of the product"""
    vendor: Optional[str] = None
    r"""The vendor of the product"""
    variants: Optional[List[Variants]] = None
    r"""The variants of the product"""
    tags: Optional[List[str]] = None
    r"""The tags associated with the product"""
    field_mappings: Optional[FieldMappingsModel] = None
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: Optional[str] = None
    r"""The UUID of the product"""
    remote_id: Optional[str] = None
    r"""The remote ID of the product in the context of the 3rd Party"""
    remote_data: Optional[RemoteData] = None
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: Optional[str] = None
    r"""The created date of the object"""
    modified_at: Optional[str] = None
    r"""The modified date of the object"""
    
