"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .unifiedticketingcommentinput import UnifiedTicketingCommentInput, UnifiedTicketingCommentInputTypedDict
from datetime import datetime
from panora_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class FieldMappingsModelTypedDict(TypedDict):
    pass
    

class FieldMappingsModel(BaseModel):
    pass
    

class RemoteDataTypedDict(TypedDict):
    pass
    

class RemoteData(BaseModel):
    pass
    

class CreatedAtTypedDict(TypedDict):
    pass
    

class CreatedAt(BaseModel):
    pass
    

class ModifiedAtTypedDict(TypedDict):
    pass
    

class ModifiedAt(BaseModel):
    pass
    

class UnifiedTicketingTicketOutputTypedDict(TypedDict):
    name: str
    r"""The name of the ticket"""
    description: str
    r"""The description of the ticket"""
    field_mappings: FieldMappingsModelTypedDict
    remote_data: RemoteDataTypedDict
    created_at: CreatedAtTypedDict
    modified_at: ModifiedAtTypedDict
    status: NotRequired[str]
    r"""The status of the ticket. Authorized values are OPEN or CLOSED."""
    due_date: NotRequired[datetime]
    r"""The date the ticket is due"""
    type: NotRequired[str]
    r"""The type of the ticket. Authorized values are PROBLEM, QUESTION, or TASK"""
    parent_ticket: NotRequired[str]
    r"""The UUID of the parent ticket"""
    collections: NotRequired[str]
    r"""The collection UUIDs the ticket belongs to"""
    tags: NotRequired[List[str]]
    r"""The tags names of the ticket"""
    completed_at: NotRequired[datetime]
    r"""The date the ticket has been completed"""
    priority: NotRequired[str]
    r"""The priority of the ticket. Authorized values are HIGH, MEDIUM or LOW."""
    assigned_to: NotRequired[List[str]]
    r"""The users UUIDs the ticket is assigned to"""
    comment: NotRequired[UnifiedTicketingCommentInputTypedDict]
    r"""The comment of the ticket"""
    account_id: NotRequired[str]
    r"""The UUID of the account which the ticket belongs to"""
    contact_id: NotRequired[str]
    r"""The UUID of the contact which the ticket belongs to"""
    attachments: NotRequired[List[str]]
    r"""The attachements UUIDs tied to the ticket"""
    id: NotRequired[str]
    r"""The UUID of the ticket"""
    remote_id: NotRequired[str]
    r"""The id of the ticket in the context of the 3rd Party"""
    

class UnifiedTicketingTicketOutput(BaseModel):
    name: str
    r"""The name of the ticket"""
    description: str
    r"""The description of the ticket"""
    field_mappings: FieldMappingsModel
    remote_data: RemoteData
    created_at: CreatedAt
    modified_at: ModifiedAt
    status: Optional[str] = None
    r"""The status of the ticket. Authorized values are OPEN or CLOSED."""
    due_date: Optional[datetime] = None
    r"""The date the ticket is due"""
    type: Optional[str] = None
    r"""The type of the ticket. Authorized values are PROBLEM, QUESTION, or TASK"""
    parent_ticket: Optional[str] = None
    r"""The UUID of the parent ticket"""
    collections: Optional[str] = None
    r"""The collection UUIDs the ticket belongs to"""
    tags: Optional[List[str]] = None
    r"""The tags names of the ticket"""
    completed_at: Optional[datetime] = None
    r"""The date the ticket has been completed"""
    priority: Optional[str] = None
    r"""The priority of the ticket. Authorized values are HIGH, MEDIUM or LOW."""
    assigned_to: Optional[List[str]] = None
    r"""The users UUIDs the ticket is assigned to"""
    comment: Optional[UnifiedTicketingCommentInput] = None
    r"""The comment of the ticket"""
    account_id: Optional[str] = None
    r"""The UUID of the account which the ticket belongs to"""
    contact_id: Optional[str] = None
    r"""The UUID of the contact which the ticket belongs to"""
    attachments: Optional[List[str]] = None
    r"""The attachements UUIDs tied to the ticket"""
    id: Optional[str] = None
    r"""The UUID of the ticket"""
    remote_id: Optional[str] = None
    r"""The id of the ticket in the context of the 3rd Party"""
    
