"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedFilestorageFileOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageFileOutputFieldMappings(BaseModel):
    pass
    

class UnifiedFilestorageFileOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageFileOutputRemoteData(BaseModel):
    pass
    

class UnifiedFilestorageFileOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageFileOutputCreatedAt(BaseModel):
    pass
    

class UnifiedFilestorageFileOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedFilestorageFileOutputModifiedAt(BaseModel):
    pass
    

class UnifiedFilestorageFileOutputTypedDict(TypedDict):
    name: str
    r"""The name of the file"""
    file_url: str
    r"""The url of the file"""
    mime_type: str
    r"""The mime type of the file"""
    size: str
    r"""The size of the file"""
    folder_id: str
    r"""The UUID of the folder tied to the file"""
    permission: str
    r"""The UUID of the permission tied to the file"""
    shared_link: str
    r"""The UUID of the shared link tied to the file"""
    field_mappings: UnifiedFilestorageFileOutputFieldMappingsTypedDict
    remote_data: UnifiedFilestorageFileOutputRemoteDataTypedDict
    created_at: UnifiedFilestorageFileOutputCreatedAtTypedDict
    modified_at: UnifiedFilestorageFileOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the file"""
    remote_id: NotRequired[str]
    r"""The id of the file in the context of the 3rd Party"""
    

class UnifiedFilestorageFileOutput(BaseModel):
    name: str
    r"""The name of the file"""
    file_url: str
    r"""The url of the file"""
    mime_type: str
    r"""The mime type of the file"""
    size: str
    r"""The size of the file"""
    folder_id: str
    r"""The UUID of the folder tied to the file"""
    permission: str
    r"""The UUID of the permission tied to the file"""
    shared_link: str
    r"""The UUID of the shared link tied to the file"""
    field_mappings: UnifiedFilestorageFileOutputFieldMappings
    remote_data: UnifiedFilestorageFileOutputRemoteData
    created_at: UnifiedFilestorageFileOutputCreatedAt
    modified_at: UnifiedFilestorageFileOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the file"""
    remote_id: Optional[str] = None
    r"""The id of the file in the context of the 3rd Party"""
    
