"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsAttachmentOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsAttachmentOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsAttachmentOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsAttachmentOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsAttachmentOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsAttachmentOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsAttachmentOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsAttachmentOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsAttachmentOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsAttachmentOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsAttachmentOutputRemoteDataTypedDict
    created_at: UnifiedAtsAttachmentOutputCreatedAtTypedDict
    modified_at: UnifiedAtsAttachmentOutputModifiedAtTypedDict
    file_url: NotRequired[str]
    r"""The URL of the file"""
    file_name: NotRequired[str]
    r"""The name of the file"""
    attachment_type: NotRequired[str]
    r"""The type of the file"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the attachment"""
    remote_modified_at: NotRequired[datetime]
    r"""The remote modification date of the attachment"""
    candidate_id: NotRequired[str]
    r"""The UUID of the candidate"""
    id: NotRequired[str]
    r"""The UUID of the attachment"""
    remote_id: NotRequired[str]
    r"""The remote ID of the attachment"""
    

class UnifiedAtsAttachmentOutput(BaseModel):
    field_mappings: UnifiedAtsAttachmentOutputFieldMappings
    remote_data: UnifiedAtsAttachmentOutputRemoteData
    created_at: UnifiedAtsAttachmentOutputCreatedAt
    modified_at: UnifiedAtsAttachmentOutputModifiedAt
    file_url: Optional[str] = None
    r"""The URL of the file"""
    file_name: Optional[str] = None
    r"""The name of the file"""
    attachment_type: Optional[str] = None
    r"""The type of the file"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the attachment"""
    remote_modified_at: Optional[datetime] = None
    r"""The remote modification date of the attachment"""
    candidate_id: Optional[str] = None
    r"""The UUID of the candidate"""
    id: Optional[str] = None
    r"""The UUID of the attachment"""
    remote_id: Optional[str] = None
    r"""The remote ID of the attachment"""
    
