"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class AddressesModelTypedDict(TypedDict):
    pass
    

class AddressesModel(BaseModel):
    pass
    

class UnifiedEcommerceCustomerOutputFieldMappingsTypedDict(TypedDict):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceCustomerOutputFieldMappings(BaseModel):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceCustomerOutputRemoteDataTypedDict(TypedDict):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceCustomerOutputRemoteData(BaseModel):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceCustomerOutputTypedDict(TypedDict):
    email: NotRequired[str]
    r"""The email of the customer"""
    first_name: NotRequired[str]
    r"""The first name of the customer"""
    last_name: NotRequired[str]
    r"""The last name of the customer"""
    phone_number: NotRequired[str]
    r"""The phone number of the customer"""
    addresses: NotRequired[List[AddressesModelTypedDict]]
    r"""The addresses of the customer"""
    field_mappings: NotRequired[UnifiedEcommerceCustomerOutputFieldMappingsTypedDict]
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: NotRequired[str]
    r"""The UUID of the customer"""
    remote_id: NotRequired[str]
    r"""The remote ID of the customer in the context of the 3rd Party"""
    remote_data: NotRequired[UnifiedEcommerceCustomerOutputRemoteDataTypedDict]
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: NotRequired[str]
    r"""The created date of the object"""
    modified_at: NotRequired[str]
    r"""The modified date of the object"""
    

class UnifiedEcommerceCustomerOutput(BaseModel):
    email: Optional[str] = None
    r"""The email of the customer"""
    first_name: Optional[str] = None
    r"""The first name of the customer"""
    last_name: Optional[str] = None
    r"""The last name of the customer"""
    phone_number: Optional[str] = None
    r"""The phone number of the customer"""
    addresses: Optional[List[AddressesModel]] = None
    r"""The addresses of the customer"""
    field_mappings: Optional[UnifiedEcommerceCustomerOutputFieldMappings] = None
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: Optional[str] = None
    r"""The UUID of the customer"""
    remote_id: Optional[str] = None
    r"""The remote ID of the customer in the context of the 3rd Party"""
    remote_data: Optional[UnifiedEcommerceCustomerOutputRemoteData] = None
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: Optional[str] = None
    r"""The created date of the object"""
    modified_at: Optional[str] = None
    r"""The modified date of the object"""
    
