"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsOfficeOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfficeOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsOfficeOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfficeOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsOfficeOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfficeOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsOfficeOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsOfficeOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsOfficeOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsOfficeOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsOfficeOutputRemoteDataTypedDict
    created_at: UnifiedAtsOfficeOutputCreatedAtTypedDict
    modified_at: UnifiedAtsOfficeOutputModifiedAtTypedDict
    name: NotRequired[str]
    r"""The name of the office"""
    location: NotRequired[str]
    r"""The location of the office"""
    id: NotRequired[str]
    r"""The UUID of the office"""
    remote_id: NotRequired[str]
    r"""The remote ID of the office in the context of the 3rd Party"""
    

class UnifiedAtsOfficeOutput(BaseModel):
    field_mappings: UnifiedAtsOfficeOutputFieldMappings
    remote_data: UnifiedAtsOfficeOutputRemoteData
    created_at: UnifiedAtsOfficeOutputCreatedAt
    modified_at: UnifiedAtsOfficeOutputModifiedAt
    name: Optional[str] = None
    r"""The name of the office"""
    location: Optional[str] = None
    r"""The location of the office"""
    id: Optional[str] = None
    r"""The UUID of the office"""
    remote_id: Optional[str] = None
    r"""The remote ID of the office in the context of the 3rd Party"""
    
