"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedEcommerceFulfillmentOutputItemsTypedDict(TypedDict):
    r"""The items in the fulfilment"""
    
    

class UnifiedEcommerceFulfillmentOutputItems(BaseModel):
    r"""The items in the fulfilment"""
    
    

class UnifiedEcommerceFulfillmentOutputFieldMappingsTypedDict(TypedDict):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceFulfillmentOutputFieldMappings(BaseModel):
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    
    

class UnifiedEcommerceFulfillmentOutputRemoteDataTypedDict(TypedDict):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceFulfillmentOutputRemoteData(BaseModel):
    r"""The remote data of the customer in the context of the 3rd Party"""
    
    

class UnifiedEcommerceFulfillmentOutputTypedDict(TypedDict):
    carrier: NotRequired[str]
    r"""The carrier of the fulfilment"""
    tracking_urls: NotRequired[List[str]]
    r"""The tracking URLs of the fulfilment"""
    tracking_numbers: NotRequired[List[str]]
    r"""The tracking numbers of the fulfilment"""
    items: NotRequired[UnifiedEcommerceFulfillmentOutputItemsTypedDict]
    r"""The items in the fulfilment"""
    order_id: NotRequired[str]
    r"""The UUID of the order associated with the fulfilment"""
    field_mappings: NotRequired[UnifiedEcommerceFulfillmentOutputFieldMappingsTypedDict]
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: NotRequired[str]
    r"""The UUID of the fulfilment"""
    remote_id: NotRequired[str]
    r"""The remote ID of the fulfilment in the context of the 3rd Party"""
    remote_data: NotRequired[UnifiedEcommerceFulfillmentOutputRemoteDataTypedDict]
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: NotRequired[str]
    r"""The created date of the object"""
    modified_at: NotRequired[str]
    r"""The modified date of the object"""
    

class UnifiedEcommerceFulfillmentOutput(BaseModel):
    carrier: Optional[str] = None
    r"""The carrier of the fulfilment"""
    tracking_urls: Optional[List[str]] = None
    r"""The tracking URLs of the fulfilment"""
    tracking_numbers: Optional[List[str]] = None
    r"""The tracking numbers of the fulfilment"""
    items: Optional[UnifiedEcommerceFulfillmentOutputItems] = None
    r"""The items in the fulfilment"""
    order_id: Optional[str] = None
    r"""The UUID of the order associated with the fulfilment"""
    field_mappings: Optional[UnifiedEcommerceFulfillmentOutputFieldMappings] = None
    r"""The custom field mappings of the object between the remote 3rd party & Panora"""
    id: Optional[str] = None
    r"""The UUID of the fulfilment"""
    remote_id: Optional[str] = None
    r"""The remote ID of the fulfilment in the context of the 3rd Party"""
    remote_data: Optional[UnifiedEcommerceFulfillmentOutputRemoteData] = None
    r"""The remote data of the customer in the context of the 3rd Party"""
    created_at: Optional[str] = None
    r"""The created date of the object"""
    modified_at: Optional[str] = None
    r"""The modified date of the object"""
    
