"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import TypedDict


class UnifiedAccountingCashflowstatementOutputTypedDict(TypedDict):
    pass
    

class UnifiedAccountingCashflowstatementOutput(BaseModel):
    pass
    
