"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from panora_sdk.types import BaseModel
from typing import Any, Dict, Optional, TypedDict
from typing_extensions import NotRequired


class VerifyEventResponseBodyTypedDict(TypedDict):
    data: NotRequired[Dict[str, Any]]
    r"""Dynamic event payload"""
    

class VerifyEventResponseBody(BaseModel):
    data: Optional[Dict[str, Any]] = None
    r"""Dynamic event payload"""
    
