"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import TypedDict


class AddressTypedDict(TypedDict):
    street_1: str
    r"""The street"""
    street_2: str
    r"""More information about the street"""
    city: str
    r"""The city"""
    state: str
    r"""The state"""
    postal_code: str
    r"""The postal code"""
    country: str
    r"""The country"""
    address_type: str
    r"""The address type. Authorized values are either PERSONAL or WORK."""
    owner_type: str
    r"""The owner type of the address"""
    

class Address(BaseModel):
    street_1: str
    r"""The street"""
    street_2: str
    r"""More information about the street"""
    city: str
    r"""The city"""
    state: str
    r"""The state"""
    postal_code: str
    r"""The postal code"""
    country: str
    r"""The country"""
    address_type: str
    r"""The address type. Authorized values are either PERSONAL or WORK."""
    owner_type: str
    r"""The owner type of the address"""
    
