"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import List, TypedDict


class CreateBatchLinkedUserDtoTypedDict(TypedDict):
    linked_user_origin_ids: List[str]
    alias: str
    

class CreateBatchLinkedUserDto(BaseModel):
    linked_user_origin_ids: List[str]
    alias: str
    
