"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import TypedDict


class DefineTargetFieldDtoTypedDict(TypedDict):
    object_type_owner: str
    name: str
    description: str
    data_type: str
    

class DefineTargetFieldDto(BaseModel):
    object_type_owner: str
    name: str
    description: str
    data_type: str
    
