"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class MapFieldToProviderDtoTypedDict(TypedDict):
    attribute_id: str
    source_custom_field_id: str
    source_provider: str
    linked_user_id: str
    

class MapFieldToProviderDto(BaseModel):
    attribute_id: Annotated[str, pydantic.Field(alias="attributeId")]
    source_custom_field_id: str
    source_provider: str
    linked_user_id: str
    
