"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class Method(str, Enum):
    GET = "GET"
    POST = "POST"
    PATCH = "PATCH"
    DELETE = "DELETE"
    PUT = "PUT"

class DataTypedDict(TypedDict):
    pass
    

class Data(BaseModel):
    pass
    

class HeadersTypedDict(TypedDict):
    pass
    

class Headers(BaseModel):
    pass
    

class PassThroughRequestDtoTypedDict(TypedDict):
    method: Method
    path: str
    data: NotRequired[DataTypedDict]
    headers: NotRequired[HeadersTypedDict]
    

class PassThroughRequestDto(BaseModel):
    method: Method
    path: str
    data: Optional[Data] = None
    headers: Optional[Headers] = None
    
