"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .passthroughrequestdto import PassThroughRequestDto, PassThroughRequestDtoTypedDict
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class RequestRequestTypedDict(TypedDict):
    integration_id: str
    linked_user_id: str
    vertical: str
    pass_through_request_dto: PassThroughRequestDtoTypedDict
    

class RequestRequest(BaseModel):
    integration_id: Annotated[str, pydantic.Field(alias="integrationId"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    linked_user_id: Annotated[str, pydantic.Field(alias="linkedUserId"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    vertical: Annotated[str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    pass_through_request_dto: Annotated[PassThroughRequestDto, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    
