"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, PathParamMetadata
from typing import TypedDict
from typing_extensions import Annotated


class StatusRequestTypedDict(TypedDict):
    vertical: str
    

class StatusRequest(BaseModel):
    vertical: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    
