"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from .email import Email, EmailTypedDict
from .phone import Phone, PhoneTypedDict
from openapi.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmCompanyOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmCompanyOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmCompanyOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmCompanyOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmCompanyOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmCompanyOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmCompanyOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmCompanyOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmCompanyOutputTypedDict(TypedDict):
    name: str
    r"""The name of the company"""
    field_mappings: UnifiedCrmCompanyOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmCompanyOutputRemoteDataTypedDict
    created_at: UnifiedCrmCompanyOutputCreatedAtTypedDict
    modified_at: UnifiedCrmCompanyOutputModifiedAtTypedDict
    industry: NotRequired[str]
    r"""The industry of the company. Authorized values can be found in the Industry enum."""
    number_of_employees: NotRequired[float]
    r"""The number of employees of the company"""
    user_id: NotRequired[str]
    r"""The UUID of the user who owns the company"""
    email_addresses: NotRequired[List[EmailTypedDict]]
    r"""The email addresses of the company"""
    addresses: NotRequired[List[AddressTypedDict]]
    r"""The addresses of the company"""
    phone_numbers: NotRequired[List[PhoneTypedDict]]
    r"""The phone numbers of the company"""
    id: NotRequired[str]
    r"""The UUID of the company"""
    remote_id: NotRequired[str]
    r"""The id of the company in the context of the Crm 3rd Party"""
    

class UnifiedCrmCompanyOutput(BaseModel):
    name: str
    r"""The name of the company"""
    field_mappings: UnifiedCrmCompanyOutputFieldMappings
    remote_data: UnifiedCrmCompanyOutputRemoteData
    created_at: UnifiedCrmCompanyOutputCreatedAt
    modified_at: UnifiedCrmCompanyOutputModifiedAt
    industry: Optional[str] = None
    r"""The industry of the company. Authorized values can be found in the Industry enum."""
    number_of_employees: Optional[float] = None
    r"""The number of employees of the company"""
    user_id: Optional[str] = None
    r"""The UUID of the user who owns the company"""
    email_addresses: Optional[List[Email]] = None
    r"""The email addresses of the company"""
    addresses: Optional[List[Address]] = None
    r"""The addresses of the company"""
    phone_numbers: Optional[List[Phone]] = None
    r"""The phone numbers of the company"""
    id: Optional[str] = None
    r"""The UUID of the company"""
    remote_id: Optional[str] = None
    r"""The id of the company in the context of the Crm 3rd Party"""
    
