"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmUserOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmUserOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmUserOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmUserOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmUserOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmUserOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmUserOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmUserOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmUserOutputTypedDict(TypedDict):
    name: str
    r"""The name of the user"""
    email: str
    r"""The email of the user"""
    field_mappings: UnifiedCrmUserOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmUserOutputRemoteDataTypedDict
    created_at: UnifiedCrmUserOutputCreatedAtTypedDict
    modified_at: UnifiedCrmUserOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the user"""
    remote_id: NotRequired[str]
    r"""The id of the user in the context of the Crm 3rd Party"""
    

class UnifiedCrmUserOutput(BaseModel):
    name: str
    r"""The name of the user"""
    email: str
    r"""The email of the user"""
    field_mappings: UnifiedCrmUserOutputFieldMappings
    remote_data: UnifiedCrmUserOutputRemoteData
    created_at: UnifiedCrmUserOutputCreatedAt
    modified_at: UnifiedCrmUserOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the user"""
    remote_id: Optional[str] = None
    r"""The id of the user in the context of the Crm 3rd Party"""
    
