"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmStageOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmStageOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmStageOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmStageOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmStageOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmStageOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmStageOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmStageOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmStageOutputTypedDict(TypedDict):
    stage_name: str
    r"""The name of the stage"""
    field_mappings: UnifiedCrmStageOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmStageOutputRemoteDataTypedDict
    created_at: UnifiedCrmStageOutputCreatedAtTypedDict
    modified_at: UnifiedCrmStageOutputModifiedAtTypedDict
    id: NotRequired[str]
    r"""The UUID of the stage"""
    remote_id: NotRequired[str]
    r"""The id of the stage in the context of the Crm 3rd Party"""
    

class UnifiedCrmStageOutput(BaseModel):
    stage_name: str
    r"""The name of the stage"""
    field_mappings: UnifiedCrmStageOutputFieldMappings
    remote_data: UnifiedCrmStageOutputRemoteData
    created_at: UnifiedCrmStageOutputCreatedAt
    modified_at: UnifiedCrmStageOutputModifiedAt
    id: Optional[str] = None
    r"""The UUID of the stage"""
    remote_id: Optional[str] = None
    r"""The id of the stage in the context of the Crm 3rd Party"""
    
