"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmNoteInputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmNoteInputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmNoteInputTypedDict(TypedDict):
    content: str
    r"""The content of the note"""
    field_mappings: UnifiedCrmNoteInputFieldMappingsTypedDict
    user_id: NotRequired[str]
    r"""The UUID of the user tied the note"""
    company_id: NotRequired[str]
    r"""The UUID of the company tied to the note"""
    contact_id: NotRequired[str]
    r"""The UUID fo the contact tied to the note"""
    deal_id: NotRequired[str]
    r"""The UUID of the deal tied to the note"""
    

class UnifiedCrmNoteInput(BaseModel):
    content: str
    r"""The content of the note"""
    field_mappings: UnifiedCrmNoteInputFieldMappings
    user_id: Optional[str] = None
    r"""The UUID of the user tied the note"""
    company_id: Optional[str] = None
    r"""The UUID of the company tied to the note"""
    contact_id: Optional[str] = None
    r"""The UUID fo the contact tied to the note"""
    deal_id: Optional[str] = None
    r"""The UUID of the deal tied to the note"""
    
