"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsScorecardOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsScorecardOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsScorecardOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsScorecardOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsScorecardOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsScorecardOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsScorecardOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsScorecardOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsScorecardOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsScorecardOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsScorecardOutputRemoteDataTypedDict
    created_at: UnifiedAtsScorecardOutputCreatedAtTypedDict
    modified_at: UnifiedAtsScorecardOutputModifiedAtTypedDict
    overall_recommendation: NotRequired[str]
    r"""The overall recommendation"""
    application_id: NotRequired[str]
    r"""The UUID of the application"""
    interview_id: NotRequired[str]
    r"""The UUID of the interview"""
    remote_created_at: NotRequired[datetime]
    r"""The remote creation date of the scorecard"""
    submitted_at: NotRequired[datetime]
    r"""The submission date of the scorecard"""
    id: NotRequired[str]
    r"""The UUID of the scorecard"""
    remote_id: NotRequired[str]
    r"""The remote ID of the scorecard in the context of the 3rd Party"""
    

class UnifiedAtsScorecardOutput(BaseModel):
    field_mappings: UnifiedAtsScorecardOutputFieldMappings
    remote_data: UnifiedAtsScorecardOutputRemoteData
    created_at: UnifiedAtsScorecardOutputCreatedAt
    modified_at: UnifiedAtsScorecardOutputModifiedAt
    overall_recommendation: Optional[str] = None
    r"""The overall recommendation"""
    application_id: Optional[str] = None
    r"""The UUID of the application"""
    interview_id: Optional[str] = None
    r"""The UUID of the interview"""
    remote_created_at: Optional[datetime] = None
    r"""The remote creation date of the scorecard"""
    submitted_at: Optional[datetime] = None
    r"""The submission date of the scorecard"""
    id: Optional[str] = None
    r"""The UUID of the scorecard"""
    remote_id: Optional[str] = None
    r"""The remote ID of the scorecard in the context of the 3rd Party"""
    
