"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from openapi.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedAtsApplicationOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedAtsApplicationOutputFieldMappings(BaseModel):
    pass
    

class UnifiedAtsApplicationOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedAtsApplicationOutputRemoteData(BaseModel):
    pass
    

class UnifiedAtsApplicationOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsApplicationOutputCreatedAt(BaseModel):
    pass
    

class UnifiedAtsApplicationOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedAtsApplicationOutputModifiedAt(BaseModel):
    pass
    

class UnifiedAtsApplicationOutputTypedDict(TypedDict):
    field_mappings: UnifiedAtsApplicationOutputFieldMappingsTypedDict
    remote_data: UnifiedAtsApplicationOutputRemoteDataTypedDict
    created_at: UnifiedAtsApplicationOutputCreatedAtTypedDict
    modified_at: UnifiedAtsApplicationOutputModifiedAtTypedDict
    applied_at: NotRequired[datetime]
    r"""The application date"""
    rejected_at: NotRequired[datetime]
    r"""The rejection date"""
    offers: NotRequired[List[str]]
    r"""The offers UUIDs for the application"""
    source: NotRequired[str]
    r"""The source of the application"""
    credited_to: NotRequired[str]
    r"""The UUID of the person credited for the application"""
    current_stage: NotRequired[str]
    r"""The UUID of the current stage of the application"""
    reject_reason: NotRequired[str]
    r"""The rejection reason for the application"""
    candidate_id: NotRequired[str]
    r"""The UUID of the candidate"""
    job_id: NotRequired[str]
    r"""The UUID of the job"""
    id: NotRequired[str]
    r"""The UUID of the application"""
    remote_id: NotRequired[str]
    r"""The remote ID of the application in the context of the 3rd Party"""
    

class UnifiedAtsApplicationOutput(BaseModel):
    field_mappings: UnifiedAtsApplicationOutputFieldMappings
    remote_data: UnifiedAtsApplicationOutputRemoteData
    created_at: UnifiedAtsApplicationOutputCreatedAt
    modified_at: UnifiedAtsApplicationOutputModifiedAt
    applied_at: Optional[datetime] = None
    r"""The application date"""
    rejected_at: Optional[datetime] = None
    r"""The rejection date"""
    offers: Optional[List[str]] = None
    r"""The offers UUIDs for the application"""
    source: Optional[str] = None
    r"""The source of the application"""
    credited_to: Optional[str] = None
    r"""The UUID of the person credited for the application"""
    current_stage: Optional[str] = None
    r"""The UUID of the current stage of the application"""
    reject_reason: Optional[str] = None
    r"""The rejection reason for the application"""
    candidate_id: Optional[str] = None
    r"""The UUID of the candidate"""
    job_id: Optional[str] = None
    r"""The UUID of the job"""
    id: Optional[str] = None
    r"""The UUID of the application"""
    remote_id: Optional[str] = None
    r"""The remote ID of the application in the context of the 3rd Party"""
    
