"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmDealOutputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmDealOutputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmDealOutputRemoteDataTypedDict(TypedDict):
    pass
    

class UnifiedCrmDealOutputRemoteData(BaseModel):
    pass
    

class UnifiedCrmDealOutputCreatedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmDealOutputCreatedAt(BaseModel):
    pass
    

class UnifiedCrmDealOutputModifiedAtTypedDict(TypedDict):
    pass
    

class UnifiedCrmDealOutputModifiedAt(BaseModel):
    pass
    

class UnifiedCrmDealOutputTypedDict(TypedDict):
    name: str
    r"""The name of the deal"""
    description: str
    r"""The description of the deal"""
    amount: float
    r"""The amount of the deal"""
    field_mappings: UnifiedCrmDealOutputFieldMappingsTypedDict
    remote_data: UnifiedCrmDealOutputRemoteDataTypedDict
    created_at: UnifiedCrmDealOutputCreatedAtTypedDict
    modified_at: UnifiedCrmDealOutputModifiedAtTypedDict
    user_id: NotRequired[str]
    r"""The UUID of the user who is on the deal"""
    stage_id: NotRequired[str]
    r"""The UUID of the stage of the deal"""
    company_id: NotRequired[str]
    r"""The UUID of the company tied to the deal"""
    id: NotRequired[str]
    r"""The UUID of the deal"""
    remote_id: NotRequired[str]
    r"""The id of the deal in the context of the Crm 3rd Party"""
    

class UnifiedCrmDealOutput(BaseModel):
    name: str
    r"""The name of the deal"""
    description: str
    r"""The description of the deal"""
    amount: float
    r"""The amount of the deal"""
    field_mappings: UnifiedCrmDealOutputFieldMappings
    remote_data: UnifiedCrmDealOutputRemoteData
    created_at: UnifiedCrmDealOutputCreatedAt
    modified_at: UnifiedCrmDealOutputModifiedAt
    user_id: Optional[str] = None
    r"""The UUID of the user who is on the deal"""
    stage_id: Optional[str] = None
    r"""The UUID of the stage of the deal"""
    company_id: Optional[str] = None
    r"""The UUID of the company tied to the deal"""
    id: Optional[str] = None
    r"""The UUID of the deal"""
    remote_id: Optional[str] = None
    r"""The id of the deal in the context of the Crm 3rd Party"""
    
