"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import TypedDict


class UnifiedCampaignOutputTypedDict(TypedDict):
    pass
    

class UnifiedCampaignOutput(BaseModel):
    pass
    
