"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from .email import Email, EmailTypedDict
from .phone import Phone, PhoneTypedDict
from openapi.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UnifiedCrmCompanyInputFieldMappingsTypedDict(TypedDict):
    pass
    

class UnifiedCrmCompanyInputFieldMappings(BaseModel):
    pass
    

class UnifiedCrmCompanyInputTypedDict(TypedDict):
    name: str
    r"""The name of the company"""
    field_mappings: UnifiedCrmCompanyInputFieldMappingsTypedDict
    industry: NotRequired[str]
    r"""The industry of the company. Authorized values can be found in the Industry enum."""
    number_of_employees: NotRequired[float]
    r"""The number of employees of the company"""
    user_id: NotRequired[str]
    r"""The UUID of the user who owns the company"""
    email_addresses: NotRequired[List[EmailTypedDict]]
    r"""The email addresses of the company"""
    addresses: NotRequired[List[AddressTypedDict]]
    r"""The addresses of the company"""
    phone_numbers: NotRequired[List[PhoneTypedDict]]
    r"""The phone numbers of the company"""
    

class UnifiedCrmCompanyInput(BaseModel):
    name: str
    r"""The name of the company"""
    field_mappings: UnifiedCrmCompanyInputFieldMappings
    industry: Optional[str] = None
    r"""The industry of the company. Authorized values can be found in the Industry enum."""
    number_of_employees: Optional[float] = None
    r"""The number of employees of the company"""
    user_id: Optional[str] = None
    r"""The UUID of the user who owns the company"""
    email_addresses: Optional[List[Email]] = None
    r"""The email addresses of the company"""
    addresses: Optional[List[Address]] = None
    r"""The addresses of the company"""
    phone_numbers: Optional[List[Phone]] = None
    r"""The phone numbers of the company"""
    
