"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.activities import Activities
from openapi.applications import Applications
from openapi.attachments import Attachments
from openapi.candidates import Candidates
from openapi.departments import Departments
from openapi.eeocs import Eeocs
from openapi.interviews import Interviews
from openapi.jobinterviewstages import Jobinterviewstages
from openapi.jobs import Jobs
from openapi.offers import Offers
from openapi.offices import Offices
from openapi.rejectreasons import Rejectreasons
from openapi.scorecards import Scorecards
from openapi.sdk_ats_users import SDKAtsUsers
from openapi.sdk_tags import SDKTags

class Ats(BaseSDK):
    activities: Activities
    applications: Applications
    attachments: Attachments
    candidates: Candidates
    departments: Departments
    interviews: Interviews
    jobinterviewstages: Jobinterviewstages
    jobs: Jobs
    offers: Offers
    offices: Offices
    rejectreasons: Rejectreasons
    scorecards: Scorecards
    tags: SDKTags
    users: SDKAtsUsers
    eeocs: Eeocs
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.activities = Activities(self.sdk_configuration)
        self.applications = Applications(self.sdk_configuration)
        self.attachments = Attachments(self.sdk_configuration)
        self.candidates = Candidates(self.sdk_configuration)
        self.departments = Departments(self.sdk_configuration)
        self.interviews = Interviews(self.sdk_configuration)
        self.jobinterviewstages = Jobinterviewstages(self.sdk_configuration)
        self.jobs = Jobs(self.sdk_configuration)
        self.offers = Offers(self.sdk_configuration)
        self.offices = Offices(self.sdk_configuration)
        self.rejectreasons = Rejectreasons(self.sdk_configuration)
        self.scorecards = Scorecards(self.sdk_configuration)
        self.tags = SDKTags(self.sdk_configuration)
        self.users = SDKAtsUsers(self.sdk_configuration)
        self.eeocs = Eeocs(self.sdk_configuration)
    
