"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.companies import Companies
from openapi.deals import Deals
from openapi.engagements import Engagements
from openapi.notes import Notes
from openapi.sdk_contacts import SDKContacts
from openapi.sdk_users import SDKUsers
from openapi.stages import Stages
from openapi.tasks import Tasks

class Crm(BaseSDK):
    companies: Companies
    contacts: SDKContacts
    deals: Deals
    engagements: Engagements
    notes: Notes
    stages: Stages
    tasks: Tasks
    users: SDKUsers
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.companies = Companies(self.sdk_configuration)
        self.contacts = SDKContacts(self.sdk_configuration)
        self.deals = Deals(self.sdk_configuration)
        self.engagements = Engagements(self.sdk_configuration)
        self.notes = Notes(self.sdk_configuration)
        self.stages = Stages(self.sdk_configuration)
        self.tasks = Tasks(self.sdk_configuration)
        self.users = SDKUsers(self.sdk_configuration)
    
