"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.drives import Drives
from openapi.files import Files
from openapi.folders import Folders
from openapi.sdk_filestorage_users import SDKFilestorageUsers
from openapi.sdk_groups import SDKGroups

class Filestorage(BaseSDK):
    drives: Drives
    files: Files
    folders: Folders
    groups: SDKGroups
    users: SDKFilestorageUsers
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.drives = Drives(self.sdk_configuration)
        self.files = Files(self.sdk_configuration)
        self.folders = Folders(self.sdk_configuration)
        self.groups = SDKGroups(self.sdk_configuration)
        self.users = SDKFilestorageUsers(self.sdk_configuration)
    
