"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.bankinfos import Bankinfos
from openapi.benefits import Benefits
from openapi.dependents import Dependents
from openapi.employeepayrollruns import Employeepayrollruns
from openapi.employees import Employees
from openapi.employerbenefits import Employerbenefits
from openapi.employments import Employments
from openapi.groups import Groups
from openapi.locations import Locations
from openapi.paygroups import Paygroups
from openapi.payrollruns import Payrollruns
from openapi.sdk_companies import SDKCompanies
from openapi.timeoffbalances import Timeoffbalances
from openapi.timeoffs import Timeoffs

class Hris(BaseSDK):
    bankinfos: Bankinfos
    benefits: Benefits
    companies: SDKCompanies
    dependents: Dependents
    employeepayrollruns: Employeepayrollruns
    employees: Employees
    employerbenefits: Employerbenefits
    employments: Employments
    groups: Groups
    locations: Locations
    paygroups: Paygroups
    payrollruns: Payrollruns
    timeoffs: Timeoffs
    timeoffbalances: Timeoffbalances
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.bankinfos = Bankinfos(self.sdk_configuration)
        self.benefits = Benefits(self.sdk_configuration)
        self.companies = SDKCompanies(self.sdk_configuration)
        self.dependents = Dependents(self.sdk_configuration)
        self.employeepayrollruns = Employeepayrollruns(self.sdk_configuration)
        self.employees = Employees(self.sdk_configuration)
        self.employerbenefits = Employerbenefits(self.sdk_configuration)
        self.employments = Employments(self.sdk_configuration)
        self.groups = Groups(self.sdk_configuration)
        self.locations = Locations(self.sdk_configuration)
        self.paygroups = Paygroups(self.sdk_configuration)
        self.payrollruns = Payrollruns(self.sdk_configuration)
        self.timeoffs = Timeoffs(self.sdk_configuration)
        self.timeoffbalances = Timeoffbalances(self.sdk_configuration)
    
