"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.actions import Actions
from openapi.automations import Automations
from openapi.campaigns import Campaigns
from openapi.emails import Emails
from openapi.events import Events
from openapi.lists import Lists
from openapi.messages import Messages
from openapi.sdk_marketingautomation_contacts import SDKMarketingautomationContacts
from openapi.sdk_marketingautomation_users import SDKMarketingautomationUsers
from openapi.templates import Templates

class Marketingautomation(BaseSDK):
    actions: Actions
    automations: Automations
    campaigns: Campaigns
    contacts: SDKMarketingautomationContacts
    emails: Emails
    events: Events
    lists: Lists
    messages: Messages
    templates: Templates
    users: SDKMarketingautomationUsers
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.actions = Actions(self.sdk_configuration)
        self.automations = Automations(self.sdk_configuration)
        self.campaigns = Campaigns(self.sdk_configuration)
        self.contacts = SDKMarketingautomationContacts(self.sdk_configuration)
        self.emails = Emails(self.sdk_configuration)
        self.events = Events(self.sdk_configuration)
        self.lists = Lists(self.sdk_configuration)
        self.messages = Messages(self.sdk_configuration)
        self.templates = Templates(self.sdk_configuration)
        self.users = SDKMarketingautomationUsers(self.sdk_configuration)
    
