"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from openapi.accounts import Accounts
from openapi.collections import Collections
from openapi.comments import Comments
from openapi.contacts import Contacts
from openapi.sdk_ticketing_attachments import SDKTicketingAttachments
from openapi.tags import Tags
from openapi.teams import Teams
from openapi.tickets import Tickets
from openapi.users import Users

class Ticketing(BaseSDK):
    tickets: Tickets
    users: Users
    accounts: Accounts
    contacts: Contacts
    collections: Collections
    comments: Comments
    tags: Tags
    teams: Teams
    attachments: SDKTicketingAttachments
    def __init__(self, sdk_config: SDKConfiguration) -> None:
        BaseSDK.__init__(self, sdk_config)
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.tickets = Tickets(self.sdk_configuration)
        self.users = Users(self.sdk_configuration)
        self.accounts = Accounts(self.sdk_configuration)
        self.contacts = Contacts(self.sdk_configuration)
        self.collections = Collections(self.sdk_configuration)
        self.comments = Comments(self.sdk_configuration)
        self.tags = Tags(self.sdk_configuration)
        self.teams = Teams(self.sdk_configuration)
        self.attachments = SDKTicketingAttachments(self.sdk_configuration)
    
